### ISSUE TITLE
Create CLI in cli.py and in each script

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/grants_tagger#117]
At the moment we have the CLI defined in `__main__.py` to allow for the following use `python -m grants_tagger.train` which I personally never use but regardless we can define it more cleanly in its own file `cli.py` and then import the `app` in `__main__.py`.

Additionally each script should have its own cli that someone can use for example `python grants_tagger/train.py` and that CLI should be imported inside cli and assembled into the main cli we expose.

**Comment by pdan93** [comment]
Move CLI logic from `__main__.py` to `cli.py`. Have every script declare it's own cli, and the main `cli.py` just imports those for the complete CLI
