### ISSUE TITLE
Stop using aws sync in favour of dvc pull

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/grants_tagger#133]
At the moment, most data and artefacts have a dual existence. Production ones are tracked with `dvc` with everything else tracked and synced through `aws s3 sync`.

As data and models are of several GBs for this project, this creates a situation where those folders are not synced regularly and care needs to be taken from a new user when syncing to download only necessary items.

Since all experiments and pipelines should be reproducible using either a config or `dvc repro`, we should be able to delete all data and models and get them back using a simple mechanism `dvc pull`. Any non production model can be tracked separately with `dvc add` if needed. Artifacts created from running code should not be synced like we do now.

**Comment by nsorros** [comment]
@aCampello what do you feel about this? if you think its a good idea its an easy thing to do, otherwise can close and keep what we have.

**Comment by aCampello** [comment]
Definitely all input data should be pulled with dvc, but I am not sure about using it to track experiments. As long as you document the preferred way in the README, and have a step-by-step of how to push/pull experiments separately, I think it doesn't make much difference.

**Comment by nsorros** [comment]
I am closing this since there is no consensus but I feel that maybe a better time to address this is when experiments will be tracked better through dvc as we do now with #160.

Additionally a way to transition all models to experiments and align with the vision of having each model into its own folder is to create separate dvc.yaml for each approach and then either a folder per approach as we do for bertmesh or a separate file in `grants_tagger/models` And the pipeline files in one pipeline folder.
