### ISSUE TITLE
Access to this repo

### ISSUE THREAD

**Issue by ArneRobben** [wellcometrust/grants_tagger#15]
Hi Nick, 

I have made a small update together with Kirstin to the file filter_disease_codes.py, which I am trying to push as a pull request. However I get an error saying I don't have access to this repo. Would it be possible for you to grant me access? 

Thanks, 

Arne

**Comment by nsorros** [comment]
I missed that, in the future possibly you can tag me or assign an issue to me, to make sure i receive a notification. Hopefully this is resolved now.

**Comment by ArneRobben** [comment]
Thanks - the issue was indeed resolved. Will tag you in the future.
