### ISSUE TITLE
Make a recipe to push to datalabs-prod

### ISSUE THREAD

**Issue by aCampello** [wellcometrust/grants_tagger#161]

**Comment by nsorros** [comment]
To a certain extent this is self explanatory but can you add a description? For example the way things are we produce a package that production installs so how would we push to production. Production needs to update to the newest version, thats how we deploy a new model.

**Comment by nsorros** [comment]
After chating with @aCampello the problem seesm to be that in data-pipelines the models that are being used are being picked up from `datalabs-prod` bucket to which we never push.

**Comment by nsorros** [comment]
Personally I think @jdu manually copies from where we push to prod for some reason. If @jdu thinks its better to push directly to prod we can definitely do that.
