### ISSUE TITLE
Xmas shortlist 🎄

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/grants_tagger#169]
- [x] #117 
- [x] #113 
- [x] #114 
- [x] #109 
- [x] #101 
- [x] #106
- [ ] #176 
- [ ] #119 
- [ ] #178 

Active PR
- #127 
- #112 
- #173 

Active experiments
- #129 
- #128 
- #131 
- #149

**Comment by nsorros** [comment]
@aCampello I created this issue to track work before Xmas that is associated with issues. In regards to your experiments I assume that you grid search is exploring these and other settings. If any of those are not explored I am happy to run a single experiment and record the results so we can close that experiment.

**Comment by aCampello** [comment]
Yep, leave the experiments with me.

**Comment by nsorros** [comment]
Closing this as Xmas passed and we did most of those tickets
