### ISSUE TITLE
Paper experiments 📜

### ISSUE THREAD

**Issue by nsorros** [wellcometrust/grants_tagger#188]
Message to @aCampello few weeks ago
```
Competition
* more years
* full text
* larger hidden size
* optimize threshold
* ensemble

Paper
* without multilabel attention
* xtransformers
* bilstm / cnn
```
Awaiting clarification

**Comment by aCampello** [comment]
Thanks for the issue, @nsorros. Whatever experiment we think is feasible would be appreciated. It would be really ace to get XTransformers working but this seems to have become a quite hard task, and the model is really resource consuming.
 
I think I'd add to that issue some non-coding tasks:

* Choose/discuss/propose appropriate venues to send a paper
* Actually write it!

**Comment by nsorros** [comment]
I think most are feasible. Can we define feasible thought @aCampello just to ensure we are on the same page?

**Comment by aCampello** [comment]
By feasible I mean we'll have time to do it? Are we proposing to split the experiments among people mentioned in this issue ?

**Comment by nsorros** [comment]
> By feasible I mean we'll have time to do it? Are we proposing to split the experiments among people mentioned in this issue ?

I would estimate that it takes about 1 week to run depending on the experiment and 1 day to develop max. Some might take less. It does not need much involvement from others but they could jump in if needed.
